### Metody npmeryczne 1 - Lista 3

#### Zadanie 1:

Rozwiąż, bez używania komputera, układ równań $Ax=b$ metodą eliminacji Gaussa dla

$$A=\begin{pmatrix}-1 & 1 & -4\\2 & 2 & 0\\3 & 3 & 2\end{pmatrix}\quad\text{i}\quad b=\begin{pmatrix}0 \\1\\0.5\end{pmatrix}\,. $$


#### Rozwiązanie - na osobnej kartce

#### Zadanie 2:
Korzystając z rozkładu LU macierzy A rozwiąż układ równań $LUx=b$ (bez używania komputera) dla

$$L=\begin{pmatrix}1 & 0 & 0\\3/2 & 1 & 0\\1/2 & 11/13 & 1\end{pmatrix}\,,\quad U=\begin{pmatrix}2 & -3 & -1\\0 & 13/2 & -7/2\\0 & 0 & 32/13\end{pmatrix}\quad\text{i}\quad b=\begin{pmatrix}1 \\-1\\2\end{pmatrix}\,. $$

#### Rozwiązanie - na osobnej kartce

#### Zadanie 3:

Rozwiąż układ równań $Ax=b$ dla

$$A=\begin{pmatrix}0 & 0 & 2 & 1 & 2\\ 0& 1 &0 &2 &-1\\ 1 & 2 & 0 &-2 &0\\ 0 & 0 &0 &-1 &1 \\ 0 &1  &-1 &1 &-1 \end{pmatrix}\quad\text{i}\quad b=\begin{pmatrix}1 \\1\\-4\\-2\\-1\end{pmatrix}\,. $$

wykorzystując *linalg.solve* z modułu *scipy*

#### Rozwiązanie:

In [17]:
import numpy as np

a = np.array([[0, 0, 2, 1, 2], [0, 1, 0, 2, -1], [1, 2, 0, -2, 0], [0, 0, 0, -1, 1], [0, 1, -1, 1, -1]]) # tworzenie macierzy z polecenia
b = np.array([[1], [1], [-4], [-2], [-1]])# tworzenie macierzy z polecenia
r = np.linalg.solve(a, b)

print(r)


[[ 2.]
 [-2.]
 [ 1.]
 [ 1.]
 [-1.]]


#### Zadanie 4:

Napisz program do eliminacji Gaussa i użyj go do ponownego rozwiązania zadań 1 ‐ 4 z tej listy

#### Rozwiązanie:

In [15]:
import numpy as np
import scipy.linalg as linalg

x1 = np.array([[-1, 1, -4], [2, 2, 0], [3, 3, 2]]) # tworzenie macierzy z polecenia
y1 = np.array([[0], [1], [0.5]])
x2 = np.array([[2, -3, -1], [3, 2, -5], [1, 4, -1]]) # tworzenie macierzy z polecenia
y2 = np.array([[1], [-1], [2]])
x3 = np.array([[0, 0, 2, 1, 2], [0, 1, 0, 2, -1], [1, 2, 0, -2, 0], [0, 0, 0, -1, 1], [0, 1, -1, 1, -1]]) # tworzenie macierzy z polecenia
y3 = np.array([[1], [1], [-4], [-2], [-1]])

print("Zadanie 1")
print(linalg.solve(x1, y1),"\n")
print("Zadanie 2")
print(linalg.solve(x2, y2),'\n')
print("Zadanie 3")
print(linalg.solve(x3, y3),'\n')


Zadanie 1
[[ 1.25]
 [-0.75]
 [-0.5 ]] 

Zadanie 2
[[1.84375]
 [0.40625]
 [1.46875]] 

Zadanie 3
[[ 2.]
 [-2.]
 [ 1.]
 [ 1.]
 [-1.]] 



#### Zadanie 5:

Oblicz normę i wskaźnik uwarunkowania macierzy Hilberta dla n=5, 10 i 20.

#### Rozwiązanie:

In [16]:
import numpy as np
import scipy.linalg as linalg

n = np.array([5, 10, 20]) 

print("lp \t" "Norma \t\t\t","Wskaźnik ")

for i in range(0, 3):
    mh = linalg.hilbert(n[i])
    print(n[i],"\t", linalg.norm(mh),"\t", np.linalg.cond(mh))


lp 	Norma 			 Wskaźnik 
5 	 1.580906263272022 	 476607.2502425855
10 	 1.7855271226510334 	 16024416987428.36
20 	 1.9698134528699593 	 1.1484020388436145e+18
